import type { Metadata } from 'next';

import BaseLayout from '@/layout/BaseLayout';
import StyledComponentsRegistry from '@/lib/registry';
import ProgressBarProvider from '@/providers/ProgressBarProvider';
import StyledProviders from '@/providers/StyledProviders';

export const metadata: Metadata = {
  title: 'Clip Himalaya',
  description: 'Generated by create next app',
};

export default function StoreFrontRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StyledComponentsRegistry>
      <StyledProviders>
        <ProgressBarProvider>
          <BaseLayout>{children}</BaseLayout>
        </ProgressBarProvider>
      </StyledProviders>
    </StyledComponentsRegistry>
  );
}
