import type { Metadata } from 'next';

import BaseLayout from '@/layout/BaseLayout';
import StyledComponentsRegistry from '@/lib/registry';
import ProgressBarProvider from '@/providers/ProgressBarProvider';
import StyledProviders from '@/providers/StyledProviders';
import { magra, poppins } from '@/theme/fonts';

export const metadata: Metadata = {
  title: 'Clip Himalaya',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${magra.variable}`}>
        <StyledComponentsRegistry>
          <StyledProviders>
            <ProgressBarProvider>
              <BaseLayout>{children}</BaseLayout>
            </ProgressBarProvider>
          </StyledProviders>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
